enum ActionTypeEnum {
    OPEN_MODAL = "OPEN_MODAL",
    CLOSE_MODAL = "CLOSE_MODAL",

    LOAD_STATIC_HOUSE_DATA = "LOAD_STATIC_HOUSE_DATA",
    LOAD_STATIC_COMPANY_DATA = "LOAD_STATIC_COMPANY_DATA",
    LOAD_STATIC_DECORATION_DATA = "LOAD_STATIC_DECORATION_DATA",

    LOAD_MAP_DATA = "LOAD_MAP_DATA",

    LOAD_BUILDINGS = "LOAD_BUILDINGS",
    CREATE_BUILDING = "CREATE_BUILDING",
    SELECT_BUILDING = "SELECT_BUILDING",

    DESELECT_BUILDING = "DESELECT_BUILDING",

    SELECT_ACTION = "SELECT_ACTION",
    UNSELECT_ACTION = "UNSELECT_ACTION",
}

export default ActionTypeEnum;
