enum ActionTypeEnum {
    OPEN_MODAL = "OPEN_MODAL",
    CLOSE_MODAL = "CLOSE_MODAL",

    LOAD_STATIC_HOUSE_DATA = "LOAD_STATIC_HOUSE_DATA",
    LOAD_STATIC_COMPANY_DATA = "LOAD_STATIC_COMPANY_DATA",
    LOAD_STATIC_DECORATION_DATA = "LOAD_STATIC_DECORATION_DATA",

    LOAD_MAP_DATA = "LOAD_MAP_DATA",

    LOAD_BUILDINGS = "LOAD_BUILDINGS",
    UPDATE_BUILDING = "UPDATE_BUILDING",
    CREATE_BUILDING = "CREATE_BUILDING",
    MOVE_BUILDING = "MOVE_BUILDING",
    DEMOLISH_BUILDING = "DEMOLISH_BUILDING",

    SELECT_BUILDING = "SELECT_BUILDING",
    DESELECT_BUILDING = "DESELECT_BUILDING",

    SELECT_CITIZEN = "SELECT_CITIZEN",
    UNSELECT_CITIZEN = "UNSELECT_CITIZEN",

    SELECT_ACTION = "SELECT_ACTION",
    UNSELECT_ACTION = "UNSELECT_ACTION",

    LOAD_CITIZENS = "LOAD_CITIZENS",

    LOAD_USER_DATA = "LOAD_USER_DATA",
    UPDATE_CITY_NAME = "UPDATE_CITY_NAME",

    ADD_ERROR = "ADD_ERROR",
    REMOVE_ERROR = "REMOVE_ERROR",
}

export default ActionTypeEnum;
