enum ModalTypeEnum {
    BUILD_MODAL = "BUILD_MODAL",
    ACTIONS_MODAL = "ACTIONS_MODAL",
    CITIZENS_MODAL = "CITIZENS_MODAL",
    CITIZEN_ASSIGNMENT_MODAL = "CITIZEN_ASSIGNMENT_MODAL",
}

export default ModalTypeEnum;
