enum ModalTypeEnum {
    BUILD_MODAL = "BUILD_MODAL",
    ACTIONS_MODAL = "ACTIONS_MODAL",
    CITIZENS_MODAL = "CITIZENS_MODAL",
    CITIZEN_ASSIGNMENT_MODAL = "CITIZEN_ASSIGNMENT_MODAL",
    SELECT_CITIZEN_TO_DEMOLISH_MODAL = "SELECT_CITIZEN_TO_DEMOLISH_MODAL",
    CHANGE_CITY_NAME_MODAL = "CHANGE_CITY_NAME_MODAL",
    STATISTICS_MODAL = "STATISTICS_MODAL",
}

export default ModalTypeEnum;
